app_1/urls.py
from django.urls import path
from .views import (
    Listado_listView,
    Create_contacto,
    Update_contacto,
    Delete_contacto,
)


"""
    urls.py: Se encarga de gestionar las url de cada pagina dentro de la aplicacion.

"""

app_name = 'app'
urlpatterns = [
    path('', Listado_listView.as_view(), name='listar'),
    path('agregar-contacto', Create_contacto.as_view(), name='agregar'),
    path('editar-contacto/<pk>/', Update_contacto.as_view(), name='editar'),
    path('eliminar-contacto/<pk>/', Delete_contacto.as_view(), name='eliminar'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_1.urls'))
]

app_1/models.py
from django.db import models

provincias_choice = [
    ('Buenos Aires', 'Buenos Aires'),
    ('Catamarca', 'Catamarca'),
    ('Chaco', 'Chaco'),
    ('Chubut', 'Chubut'),
    ('Córdoba', 'Cordoba'),
    ('Corrientes', 'Corrientes'),
    ('Entre Ríos', 'Entre Rios'),
    ('Formosa', 'Formosa'),
    ('Jujuy', 'Jujuy'),
    ('La Pampa', 'La Pampa'),
    ('La Rioja', 'La Rioja'),
    ('Mendoza', 'Mendoza'),
    ('Misiones', 'Misiones'),
    ('Neuquén', 'Neuquen'),
    ('Río Negro', 'Rio Negro'),
    ('Salta', 'Salta'),
    ('San Juan', 'San Juan'),
    ('Santa Cruz', 'Santa Cruz'),
    ('Santa Fe', 'Santa Fe'),
    ('Santiago del Estero', 'Santiago del Estero'),
    ('Tierra del Fuego', 'Tierra del Fuego'),
    ('Tucumán', 'Tucuman'),
]


class Registros(models.Model):
    """
        Clase encargadada de crear la base de datos que almacenara los contactos
        La clase representa una tabla dentro de la base de datos
        Cada item dentro de la clase representa un campo de datos dentro de la tabla

    """
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=200)
    edad = models.SmallIntegerField()
    dni = models.IntegerField()
    provincia = models.CharField(max_length=50, choices=provincias_choice)
    fecha_creacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

app_1/forms.py
from django import forms
from .models import Registros
from django.forms import ValidationError
from crispy_forms.helper import FormHelper


class RegistroForm(forms.ModelForm):

    """
        Clase encargada de gestionar el formulario que realiza las altas de contactos a la base
        de datos.

    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.form_show_errors = True

    # declaracion del form
    class Meta:
        model = Registros
        fields = '__all__'

    # Validaciones
    ##########################################################################

    """
        clean_dni rescata el valor ingresado en el form e informa si ya existe en la
        base de datos,
        ademas valida que tenga longitud correcta.

        Ademas se agregan mas validaciones para otros campos como el nombre, apellido y edad.

    """

    def clean_dni(self):

        dni = self.cleaned_data['dni']
        len_dni = len(str(dni))
        existe = Registros.objects.filter(dni__iexact=dni).exists()

        if existe:
            raise ValidationError('Dni ya existente')
        if len_dni != 8:
            if len_dni > 8:
                faltan = len_dni - 8
                raise ValidationError(f'Longitud incorrecta, sobran {faltan} digitos.')
            else:
                faltan = 8 - len_dni
                raise ValidationError(f'Longitud incorrecta, faltan {faltan} digitos.')
        return dni

    nombre = forms.RegexField(
        regex="^[a-zA-Z]+$", error_messages={'invalid': 'Ingrese solo letras'})

    apellido = forms.RegexField(
        regex="^[a-zA-Z]+$", error_messages={'invalid': 'Ingrese solo letras'})

    edad = forms.IntegerField(max_value=100, min_value=0)


class EditForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.form_show_errors = True

    # Declaracion del form
    class Meta:
        model = Registros
        fields = ['nombre', 'apellido', 'edad', 'provincia']

    # validaciones
    nombre = forms.RegexField(
        regex="^[a-zA-Z]+$", error_messages={'invalid': 'Ingrese solo letras'})

    apellido = forms.RegexField(
        regex="^[a-zA-Z]+$", error_messages={'invalid': 'Ingrese solo letras'})

    edad = forms.IntegerField(max_value=100, min_value=0)

app_1/views.py
from django.urls import reverse_lazy
from .models import Registros
from .forms import RegistroForm, EditForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q


class Listado_listView(ListView):
    """
        Clase encargada de listar y mostrar los contactos dentro de la pagina principal.
        Aplica el metodo get_context_data para realizar la busquedad de los contactos dentro de
        la base de datos.
            Devuelve un un diccionario con la data que sera mostrada en pantalla.
    """
    model = Registros
    template_name = 'App_1/listar_contactos.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        search = self.request.GET.get('buscar', ''). split(' ')
        contactos = Registros.objects.all()
        if search:
            for s in search:
                contactos = contactos.filter(Q(nombre__icontains=s) | Q(apellido__icontains=s))

        context['contacto'] = [{
            'instancia': contacto,
            # 'form': RegistroForm(instance=contacto)
        }
            for contacto in contactos
        ]
        print(context)
        return context


class Create_contacto(SuccessMessageMixin, CreateView):
    """
        Clase encargada de gestionar la creacion de nuevos contactos
        Tambien gestiona los mensajes correspondientes a la accion

    """

    form_class = RegistroForm
    template_name = 'App_1/agregar_contactos.html'
    success_url = reverse_lazy('app:listar')
    success_message = "Contacto creado con exito"


class Update_contacto(SuccessMessageMixin, UpdateView):
    """
        Clase encargada de grstionar la actualizacion de contactos ya existentes
        Tambien gestiona los mensajes correspondieste a la accion
    """
    form_class = EditForm
    template_name = 'App_1/editar_contactos.html'
    model = Registros
    success_message = 'Contacto editado'
    success_url = reverse_lazy('app:listar')


class Delete_contacto(SuccessMessageMixin, DeleteView):
    """
        Clase encargada de gestionar la eliminacion de contactos.
        Tambien gestiona los mensajes correspondieste a la accion
    """
    model = Registros
    success_url = reverse_lazy('app:listar')

app_1/templates/App_1/agregar_contactos.html
{% extends 'App_1/base.html' %} {% block content %} {% load crispy_forms_tags %} {% load static %}
<div class="row">
  <div class="col-xl-4 offset-xl-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2">
    <div class="card">
      <div class="card-body">
        <p class="display-6">Agendar contactos</p>
        <hr />

        <form action="" method="post" id="form">
          {% csrf_token %} {{form | crispy}}

          <hr />

          <div class="d-grid gap-1">
            <button type="submit" class="btn btn-success" id="btn_success">Agendar</button>
            <a href=" {% url 'app:listar' %}" class="btn btn-danger">Atras</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app_1/templates/App_1/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %} {% load crispy_forms_tags %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />

    <title>App</title>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-success mb-5">
      <div class="container-fluid">
        <a class="navbar-brand mb-0 h1 display-3" href="{% url 'app:listar' %}"
          >Listado de contactos</a
        >
      </div>
    </nav>
    {% block content %} {% endblock %}

    <script src=" {% static 'js/bootstrap.js' %}"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="{% static 'js/script.js' %}"></script>

    {% if messages %} {% for message in messages %}
    <script>
      Swal.fire({
        title: "Felicitaciones",
        text: "{{message}}",
        icon: "success",
      });
    </script>

    {% endfor %} {% endif %}
  </body>
</html>

app_1/templates/App_1/editar_contactos.html
{% extends 'App_1/base.html' %} {% block content %} {% load crispy_forms_tags %}

<div class="row">
  <div class="col-xl-4 offset-xl-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2">
    <div class="card">
      <div class="card-body">
        <p class="display-6">Editar contactos</p>
        <hr />

        <form action="" method="POST" id="form">
          {% csrf_token %} {{ form | crispy }}

          <hr />
          <div class="d-grid gap-1">
            <button type="submit" id="btn-enviar" class="btn btn-info">Editar</button>
            <a href="{% url 'app:listar' %}" class="btn btn-danger">Atras</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app_1/templates/App_1/listar_contactos.html
{% extends 'App_1/base.html' %}\ {% block content %} {% load humanize %}

<div class="container">
  {% if contacto %}
  <!--Buscador-->
  <hr />
  <div class="row">
    <div class="col-lg-8 col-md-12">
      <form class="d-flex" method="GET">
        <input
          class="form-control me-2"
          type="search"
          placeholder="Ingrese contacto a buscar..."
          name="buscar"
          value="{{ request.GET.buscar }}"
        />
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>
  <hr />
  {% else %} {% endif%}

  <div>
    <a class="btn btn-outline-success" href="{% url 'app:agregar' %}"> Agendar contacto </a>
  </div>

  <hr />

  {% if contacto %} {% for con in contacto %}
  <div class="accordion" id="accordionFlushExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="flush-headingOne">
        <button
          class="accordion-button collapsed mb-2"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#flush-collapse{{con.instancia.id}}"
          aria-expanded="false"
          aria-controls="flush-collapseOne"
        >
          {{con.instancia.nombre | capfirst }}&nbsp;{{con.instancia.apellido | capfirst }}
        </button>
      </h2>

      <div
        id="flush-collapse{{con.instancia.id}}"
        class="accordion-collapse collapse mb-2"
        aria-labelledby="flush-headingOne"
        data-bs-parent="#accordionFlushExample"
      >
        <div class="accordion-body">
          <ul>
            <li>
              <p>Edad: {{con.instancia.edad}}</p>
            </li>
            <li>
              <p>Dni: {{con.instancia.dni | intcomma }}</p>
            </li>

            <li>
              <p>Provincia: {{con.instancia.provincia | capfirst}}</p>
            </li>
            <li>
              <hr />
              <div class="row">
                <div class="col-6">
                  <small>Fecha de creacion: {{con.instancia.fecha_creacion}}</small>
                </div>

                <!--Botones-->
                <div class="col-6 d-flex justify-content-end">
                  <a
                    class="btn btn-info"
                    id="boton_edit"
                    href="{% url 'app:editar' con.instancia.pk %}"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      fill="currentColor"
                      class="bi bi-pencil"
                      viewBox="0 0 16 16"
                    >
                      <path
                        d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"
                      />
                    </svg>
                  </a>
                  &nbsp;

                  <form
                    action="{% url 'app:eliminar' con.instancia.pk %}"
                    method="post"
                    id="form_eliminar"
                  >
                    {% csrf_token %}
                    <div class="d-grid gap-1">
                      <button type="submit" id="boton_delete" class="btn btn-danger">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          width="16"
                          height="16"
                          fill="currentColor"
                          class="bi bi-trash"
                          viewBox="0 0 16 16"
                        >
                          <path
                            d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"
                          />
                          <path
                            fill-rule="evenodd"
                            d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"
                          />
                        </svg>
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  {% endfor %} {% else %}
  <div class="alert alert-danger" role="alert">Sin contactos aun</div>
  {% endif %}
</div>

{% endblock %}